Repository Vegan-Life/VeganLife-AOS, pull requests merged in 2024-05, with the labels that each got.

#80 Feat: 커뮤니티 피드 전체보기 기능 구현 #46
  app/src/main/java/com/project/veganlife/community/data/model/Feed.kt
  app/src/main/java/com/project/veganlife/community/data/model/Feeds.kt
  app/src/main/java/com/project/veganlife/community/data/model/Pageable.kt
  app/src/main/java/com/project/veganlife/community/data/model/Sort.kt
  app/src/main/java/com/project/veganlife/community/data/remote/CommunityApi.kt
  app/src/main/java/com/project/veganlife/community/data/remote/CommunityClient.kt
  app/src/main/java/com/project/veganlife/community/data/remote/CommunityRemoteDataSource.kt
  app/src/main/java/com/project/veganlife/community/data/repositoryimpl/CommunityRepositoryImpl.kt
  app/src/main/java/com/project/veganlife/community/di/CommunityRepositoryModule.kt
  app/src/main/java/com/project/veganlife/community/domain/repository/CommunityRepository.kt
  app/src/main/java/com/project/veganlife/community/ui/adapter/FeedsAdapter.kt
  app/src/main/java/com/project/veganlife/community/ui/view/CommunityHomeFragment.kt
  app/src/main/java/com/project/veganlife/community/ui/viewmodel/FeedsGetViewModel.kt
  app/src/main/java/com/project/veganlife/login/ui/view/LoginFragment.kt
  app/src/main/java/com/project/veganlife/utils/ui/DisplayUtils.kt
  app/src/main/res/drawable/community_fab_border_background.xml
  app/src/main/res/drawable/rounded_border_button.xml
  app/src/main/res/layout/fragment_community_home.xml
  app/src/main/res/layout/fragment_recipe_home.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Feat

#81 Feat: 마이페이지 기능 구현 #74
  app/libs/oauth-5.9.0.aar
  app/src/main/java/com/project/veganlife/di/AppApiModule.kt
  app/src/main/java/com/project/veganlife/login/LoginFragment.kt
  app/src/main/java/com/project/veganlife/login/data/datasource/KakaoLoginDataSource.kt
  app/src/main/java/com/project/veganlife/login/data/datasource/LoginDataSource.kt
  app/src/main/java/com/project/veganlife/login/data/datasource/NaverLoginDataSource.kt
  app/src/main/java/com/project/veganlife/login/data/local/LocalUserDataSource.kt
  app/src/main/java/com/project/veganlife/login/data/local/LocalUserDataSourceImpl.kt
  app/src/main/java/com/project/veganlife/login/data/repositoryImpl/LoginRepositoryImpl.kt
  app/src/main/java/com/project/veganlife/login/data/repositoryImpl/UserRepositoryImpl.kt
  app/src/main/java/com/project/veganlife/login/domain/repository/LoginRepository.kt
  app/src/main/java/com/project/veganlife/login/domain/repository/UserRepository.kt
  app/src/main/java/com/project/veganlife/login/domain/usecase/LoginUsecase.kt
  app/src/main/java/com/project/veganlife/login/domain/usecase/UserUsecase.kt
  app/src/main/java/com/project/veganlife/mypage/data/datasource/MypageGetUserInfoDataSource.kt
  app/src/main/java/com/project/veganlife/mypage/data/datasource/MypageGetUserInfoDataSourceImpl.kt
  app/src/main/java/com/project/veganlife/mypage/data/datasource/MypageWithdrawalDataSource.kt
  app/src/main/java/com/project/veganlife/mypage/data/datasource/MypageWithdrawalDataSourceImpl.kt
  app/src/main/java/com/project/veganlife/mypage/data/remote/MypageGetUserInfoApi.kt
  app/src/main/java/com/project/veganlife/mypage/data/remote/MypageWithDrawalApi.kt
  app/src/main/java/com/project/veganlife/mypage/data/repositoryImpl/MypageGetUserInfoRepositoryImpl.kt
  app/src/main/java/com/project/veganlife/mypage/data/repositoryImpl/MypageWithdrawalRepositoryImpl.kt
  app/src/main/java/com/project/veganlife/mypage/di/MypageGetUserInfoModule.kt
  app/src/main/java/com/project/veganlife/mypage/di/MypageWithdrawalModule.kt
  app/src/main/java/com/project/veganlife/mypage/domain/repository/MypageGetUserRespository.kt
  app/src/main/java/com/project/veganlife/mypage/domain/repository/MypageWithdrawalRespository.kt
  app/src/main/java/com/project/veganlife/mypage/domain/usecase/MypageGetUserInfoUsecase.kt
  app/src/main/java/com/project/veganlife/mypage/domain/usecase/MypageLogoutUsecase.kt
  app/src/main/java/com/project/veganlife/mypage/domain/usecase/MypageWithdrawalUsecase.kt
  app/src/main/java/com/project/veganlife/mypage/ui/view/MypageCompletedWithdrawalFragment.kt
  app/src/main/java/com/project/veganlife/mypage/ui/view/MypageCustomDialogFragment.kt
  app/src/main/java/com/project/veganlife/mypage/ui/view/MypageHomeFragment.kt
  app/src/main/java/com/project/veganlife/mypage/ui/viewmodel/MypageLogoutWithdrawalViewmodel.kt
  app/src/main/java/com/project/veganlife/mypage/ui/viewmodel/MypageViewmodel.kt
  app/src/main/res/layout/fragment_mypage_completed_withdrawal.xml
  app/src/main/res/layout/fragment_mypage_home.xml
  app/src/main/res/layout/popup_mypage_logout.xml
  app/src/main/res/layout/popup_mypage_modify.xml
  app/src/main/res/layout/popup_mypage_withdrawal.xml
  app/src/main/res/layout/popup_recipe_delete.xml
  app/src/main/res/layout/popup_recipe_like.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: Feat

#84 Remove: 회원가입 오류 파일 삭제 #83
  app/src/main/java/com/project/veganlife/signup/SignupAddInfoFragment.kt
  app/src/main/java/com/project/veganlife/signup/SignupCompleteFragment.kt
Labels: Remove

#86 Refactor: 프로필 정보 GET 수정 #85
  app/src/main/java/com/project/veganlife/data/datasource/ProfileGetDataSource.kt
  app/src/main/java/com/project/veganlife/data/datasource/ProfileGetDataSourceImpl.kt
  app/src/main/java/com/project/veganlife/data/repositoryImpl/ProfileGetRepositoryImpl.kt
  app/src/main/java/com/project/veganlife/di/AppApiModule.kt
  app/src/main/java/com/project/veganlife/di/ProfileGetModule.kt
  app/src/main/java/com/project/veganlife/domain/repository/ProfileGetRespository.kt
  app/src/main/java/com/project/veganlife/domain/usecase/ProfileGetUsecase.kt
  app/src/main/java/com/project/veganlife/home/data/datasource/HomeHomeProfilePhotoGetDataSourceImpl.kt
  app/src/main/java/com/project/veganlife/home/data/datasource/HomeProfilePhotoGetDataSource.kt
  app/src/main/java/com/project/veganlife/home/data/repositoryImpl/HomeProfilePhotoGetRepositoryImpl.kt
  app/src/main/java/com/project/veganlife/home/di/HomeProfilePhotoModule.kt
  app/src/main/java/com/project/veganlife/home/domain/repository/HomeProfilePhotoGetRepository.kt
  app/src/main/java/com/project/veganlife/home/domain/usecase/HomeProfilePhotoUsecase.kt
  app/src/main/java/com/project/veganlife/home/ui/view/HomeFragment.kt
  app/src/main/java/com/project/veganlife/home/ui/viewmodel/HomeViewModel.kt
  app/src/main/java/com/project/veganlife/login/ui/view/LoginFragment.kt
  app/src/main/java/com/project/veganlife/mypage/data/datasource/MypageGetUserInfoDataSource.kt
  app/src/main/java/com/project/veganlife/mypage/data/remote/MypageGetUserInfoApi.kt
  app/src/main/java/com/project/veganlife/mypage/data/repositoryImpl/MypageGetUserInfoRepositoryImpl.kt
  app/src/main/java/com/project/veganlife/mypage/di/MypageGetUserInfoModule.kt
  app/src/main/java/com/project/veganlife/mypage/domain/repository/MypageGetUserRespository.kt
  app/src/main/java/com/project/veganlife/mypage/domain/usecase/MypageGetUserInfoUsecase.kt
  app/src/main/java/com/project/veganlife/mypage/ui/viewmodel/MypageViewmodel.kt
Labels: Refactor

#87 Feat: 라이프체크 일일섭취량조회 기능구현 #77
  app/src/main/java/com/project/veganlife/lifecheck/data/datasource/LifeCheckDailyIntakeDataSource.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/datasource/LifeCheckDailyIntakeDataSourceImpl.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/datasource/LifeCheckRecommendedIntakeDataSource.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/datasource/LifeCheckRecommendedIntakeDataSourceImpl.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/ropositoryImpl/LifeCheckDailyIntakeRepositoryImpl.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/ropositoryImpl/LifeCheckRecommendedIntakeRepositoryImpl.kt
  app/src/main/java/com/project/veganlife/lifecheck/di/LifeCheckModule.kt
  app/src/main/java/com/project/veganlife/lifecheck/domain/repository/LifeCheckDailyIntakeRepository.kt
  app/src/main/java/com/project/veganlife/lifecheck/domain/repository/LifeCheckRecommendedIntakeRepository.kt
  app/src/main/java/com/project/veganlife/lifecheck/domain/usecase/LifeCheckGetDailyIntakeUseCase.kt
  app/src/main/java/com/project/veganlife/lifecheck/domain/usecase/LifeCheckGetRecommendedIntakeUseCase.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/view/LifeCheckDailyFragment.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/view/LifeCheckHomeFragment.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/viewmodel/LifeCheckViewModel.kt
  build.gradle.kts
Labels: Feat
