Repository Vegan-Life/VeganLife-AOS, pull requests merged in 2024-06, with the labels that each got.

#91 Feat: 다크모드 방지 #90
  app/src/main/java/com/project/veganlife/GlobalApplication.kt
Labels: Feat

#95 Feat: 라이프체크 주간섭취칼로리 기능 구현 #88
  app/src/main/java/com/project/veganlife/di/AppApiModule.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/datasource/LifeCheckWeeklyCalorieDataSource.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/datasource/LifeCheckWeeklyCalorieDataSourceImpl.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/model/LifeCheckWeeklyCalorieResponse.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/remote/LifeCheckWeeklyCalorieGetApi.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/ropositoryImpl/LifeCheckWeeklyCalorieRepositoryImpl.kt
  app/src/main/java/com/project/veganlife/lifecheck/di/LifeCheckModule.kt
  app/src/main/java/com/project/veganlife/lifecheck/domain/repository/LifeCheckWeeklyCalorieRepository.kt
  app/src/main/java/com/project/veganlife/lifecheck/domain/usecase/LifeCheckGetWeeklyCalorieUseCase.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/view/LifeCheckHomeFragment.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/view/LifeCheckWeeklyFragment.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/viewmodel/LifeCheckViewModel.kt
Labels: Feat, Fix

#97 Feat: 라이프체크 월간섭취칼로리 기능 구현 #96
  app/src/main/java/com/project/veganlife/di/AppApiModule.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/datasource/LifeCheckMonthlyCalorieDataSource.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/datasource/LifeCheckMonthlyCalorieDataSourceImpl.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/remote/LifeCheckMonthlyCalorieGetApi.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/ropositoryImpl/LifeCheckMonthlyCalorieRepositoryImpl.kt
  app/src/main/java/com/project/veganlife/lifecheck/di/LifeCheckModule.kt
  app/src/main/java/com/project/veganlife/lifecheck/domain/repository/LifeCheckMonthlyCalorieRepository.kt
  app/src/main/java/com/project/veganlife/lifecheck/domain/usecase/LifeCheckGetMonthlyCalorieUseCase.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/view/LifeCheckHomeFragment.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/view/LifeCheckMonthlyFragment.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/viewmodel/LifeCheckViewModel.kt
  app/src/main/res/layout/picker_lifecheck_year_month.xml
Labels: Design, Feat

#99 Feat: 라이프체크 연간섭취칼로리 기능 구현 #98
  app/src/main/java/com/project/veganlife/di/AppApiModule.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/datasource/LifeCheckYearlyCalorieDataSource.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/datasource/LifeCheckYearlyCalorieDataSourceImpl.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/remote/LifeCheckYearlyCalorieGetApi.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/ropositoryImpl/LifeCheckYearlyCalorieRepositoryImpl.kt
  app/src/main/java/com/project/veganlife/lifecheck/di/LifeCheckModule.kt
  app/src/main/java/com/project/veganlife/lifecheck/domain/repository/LifeCheckYearlyCalorieRepository.kt
  app/src/main/java/com/project/veganlife/lifecheck/domain/usecase/LifeCheckGetYearlyCalorieUseCase.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/view/LifeCheckHomeFragment.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/view/LifeCheckYearlyFragment.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/viewmodel/LifeCheckViewModel.kt
Labels: Feat

#102 Feat: 라이프체크 식품데이터 목록 검색 기능 구현 #100
  app/src/main/java/com/project/veganlife/di/AppApiModule.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/datasource/LifeCheckMealDataPagingSource.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/model/LifeCheckMealData.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/remote/LifeCheckMealDataApi.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/ropositoryImpl/LifeCheckMealDataRepositoryImpl.kt
  app/src/main/java/com/project/veganlife/lifecheck/di/LifeCheckModule.kt
  app/src/main/java/com/project/veganlife/lifecheck/domain/repository/LifeCheckMealDataRepository.kt
  app/src/main/java/com/project/veganlife/lifecheck/domain/usecase/LifeCheckGetMealDataUsecase.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/adapter/LifeCheckMealDataAdapter.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/view/LifeCheckDietSelectDialogFragment.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/view/LifeCheckHomeFragment.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/view/LifeCheckMenuSearchFragment.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/viewmodel/LifeCheckViewModel.kt
  app/src/main/res/drawable/selector_lifecheck_diet_select.xml
  app/src/main/res/layout/dialog_life_check_diet_select.xml
Labels: Feat

#105 Feat: 바텀 네비게이션 사이 이동 슬라이드 애니메이션 #92
  app/src/main/java/com/project/veganlife/MainActivity.kt
  app/src/main/res/anim/slide_in_right.xml
  app/src/main/res/anim/slide_out_left.xml
Labels: Feat

#107 Feat: 라이프체크 식품데이터 등록 기능 구현 #103
  app/src/main/java/com/project/veganlife/di/AppApiModule.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/datasource/LifeCheckRegisterMealDataDataSource.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/datasource/LifeCheckRegisterMealDataDataSourceImpl.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/model/LifeCheckMealDataRequest.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/remote/LifeCheckMealDataPostApi.kt
  app/src/main/java/com/project/veganlife/lifecheck/data/ropositoryImpl/LifeCheckRegisterMealDataRepositoryImpl.kt
  app/src/main/java/com/project/veganlife/lifecheck/di/LifeCheckModule.kt
  app/src/main/java/com/project/veganlife/lifecheck/di/LifeCheckPostModule.kt
  app/src/main/java/com/project/veganlife/lifecheck/domain/repository/LifeCheckRegisterMealDataRepository.kt
  app/src/main/java/com/project/veganlife/lifecheck/domain/usecase/LifeCheckRegisterMealDataUseCase.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/view/LifeCheckMenuAddFragment.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/view/LifeCheckMenuSearchFragment.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/viewmodel/LifeCheckViewModel.kt
  app/src/main/java/com/project/veganlife/lifecheck/util/EventWrapper.kt
  app/src/main/res/drawable/lifecheck_rect_gray1_no.xml
  app/src/main/res/layout/fragment_life_check_menu_add.xml
Labels: Feat
