Repository Vegan-Life/VeganLife-AOS, pull requests merged in 2025-04, with the labels that each got.

#167 Feature/165 fix all file
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/project/veganlife/home/ui/view/HomeFragment.kt
  app/src/main/java/com/project/veganlife/login/ui/view/LoginFragment.kt
  app/src/main/java/com/project/veganlife/mypage/ui/adapter/MypagePostedCommentAdapter.kt
  app/src/main/java/com/project/veganlife/mypage/ui/adapter/MypagePostedFeedAdapter.kt
  app/src/main/java/com/project/veganlife/mypage/ui/view/MypageHomeFragment.kt
  app/src/main/java/com/project/veganlife/mypage/ui/view/MypageModifyFragment.kt
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: Feat, Fix

#168 Feat: Splash 구현 #166
  app/src/main/java/com/project/veganlife/MainActivity.kt
  app/src/main/java/com/project/veganlife/di/AppModule.kt
  app/src/main/java/com/project/veganlife/home/ui/view/HomeFragment.kt
  app/src/main/java/com/project/veganlife/splash/SplashFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_splash.xml
  app/src/main/res/values/themes.xml
Labels: Feat

#170 Chore: update target sdk 34 #169
  app/build.gradle.kts
Labels: Chore

#172 Chore: update versionCode
  app/build.gradle.kts
Labels: Chore

#174 Design: App icon 추가 및 변경
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/app_icon-playstore.png
  app/src/main/res/drawable/app_icon_background.xml
  app/src/main/res/mipmap-anydpi-v26/app_icon.xml
  app/src/main/res/mipmap-anydpi-v26/app_icon_round.xml
  app/src/main/res/mipmap-hdpi/app_icon.webp
  app/src/main/res/mipmap-hdpi/app_icon_foreground.webp
  app/src/main/res/mipmap-hdpi/app_icon_round.webp
  app/src/main/res/mipmap-mdpi/app_icon.webp
  app/src/main/res/mipmap-mdpi/app_icon_foreground.webp
  app/src/main/res/mipmap-mdpi/app_icon_round.webp
  app/src/main/res/mipmap-xhdpi/app_icon.webp
  app/src/main/res/mipmap-xhdpi/app_icon_foreground.webp
  app/src/main/res/mipmap-xhdpi/app_icon_round.webp
  app/src/main/res/mipmap-xxhdpi/app_icon.webp
  app/src/main/res/mipmap-xxhdpi/app_icon_foreground.webp
  app/src/main/res/mipmap-xxhdpi/app_icon_round.webp
  app/src/main/res/mipmap-xxxhdpi/app_icon.webp
  app/src/main/res/mipmap-xxxhdpi/app_icon_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/app_icon_round.webp
Labels: Design, Feat

#176 Design: 커뮤니티 ui 수정
  app/src/main/java/com/project/veganlife/community/ui/view/CommunityWriteFeedFragment.kt
  app/src/main/res/layout/layout_community_detail_feed_comment_input_box.xml
Labels: Design
