Repository Vegan-Life/VeganLife-AOS, pull requests merged in 2025-03, with the labels that each got.

#152 151-fix-community-popular-tag
  app/src/main/java/com/project/veganlife/community/ui/adapter/OnItemClickedListener.kt
  app/src/main/java/com/project/veganlife/community/ui/adapter/RecentSearchAdapter.kt
  app/src/main/java/com/project/veganlife/community/ui/view/CommunitySearchFragment.kt
  app/src/main/java/com/project/veganlife/community/ui/view/search/CommunitySearchAfterFragment.kt
  app/src/main/java/com/project/veganlife/community/ui/view/search/CommunitySearchBeforeFragment.kt
  app/src/main/java/com/project/veganlife/community/ui/viewmodel/RecentSearchesViewModel.kt
  app/src/main/res/layout/layout_community_search_toolbar.xml
Labels: Bug

#154 Fix: 라이프체크 수정사항 진행 #150
  app/src/main/java/com/project/veganlife/lifecheck/ui/adapter/LifeCheckDietDetailImageAdapter.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/adapter/LifeCheckMealLogListAdapter.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/view/LifeCheckDailyFragment.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/view/LifeCheckHomeFragment.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/view/LifeCheckMenuAddFragment.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/view/LifeCheckMonthlyFragment.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/view/LifeCheckWeeklyFragment.kt
  app/src/main/java/com/project/veganlife/lifecheck/ui/view/LifeCheckYearlyFragment.kt
  app/src/main/res/layout/fragment_life_check_daily.xml
  app/src/main/res/layout/fragment_life_check_menu_add.xml
  app/src/main/res/layout/fragment_life_check_menu_modify.xml
  app/src/main/res/layout/item_lifecheck_image.xml
  app/src/main/res/layout/layout_lifecheck_diet_add.xml
Labels: Fix

#157 Feat:142_마이페이지 수정 및 메뉴 기능 추가
  app/src/main/java/com/project/veganlife/home/ui/view/HomeFragment.kt
  app/src/main/java/com/project/veganlife/mypage/data/datasource/MypageProfileModifyDataSourceImpl.kt
  app/src/main/java/com/project/veganlife/mypage/data/model/MypageModifyRequestDTO.kt
  app/src/main/java/com/project/veganlife/mypage/data/repositoryImpl/MypageRepositoryImpl.kt
  app/src/main/java/com/project/veganlife/mypage/domain/repository/MypageRepository.kt
  app/src/main/java/com/project/veganlife/mypage/domain/usecase/MypageUsecase.kt
  app/src/main/java/com/project/veganlife/mypage/ui/view/MypageHomeFragment.kt
  app/src/main/java/com/project/veganlife/mypage/ui/view/MypageModifyFragment.kt
  app/src/main/java/com/project/veganlife/mypage/ui/viewmodel/MypageViewmodel.kt
  app/src/main/res/menu/menu_mypage_profile_context_menu.xml
  app/src/main/res/values/strings.xml
Labels: Feat, Fix

#158 Fix: 바텀 네비게이션 수정
  app/src/main/java/com/project/veganlife/recipe/ui/view/RecipeDeleteDialogFragment.kt
Labels: Fix

#162 159-fix-post-detail
  app/src/main/java/com/project/veganlife/community/ui/view/CommunityDetailFeedFragment.kt
Labels: Fix

#164 Design: 레시피 홈 item size 수정
  app/src/main/res/layout/item_recyclerview_recipe_list.xml
Labels: Design
